site_name: Runge Kutta 4

theme:
  name: "material"

nav:
  - index.md
  - explanation.md
  - tutorials.md
  - reference.md

plugins:
  - mkdocstrings

markdown_extension:
  - pymarkdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
